# Generated by Django 4.1.5 on 2023-03-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userexam_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscoreexam',
            old_name='id_user',
            new_name='user',
        ),
    ]
