# Generated by Django 4.1.5 on 2023-03-31 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_id_user_userscoreexam_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscorequiz',
            old_name='id_user',
            new_name='user',
        ),
    ]
