# Generated by Django 4.1.5 on 2023-03-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_id_user_userscorequiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='piece_recto',
            field=models.ImageField(blank=True, null=True, upload_to='./field360App/media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='piece_verso',
            field=models.ImageField(blank=True, null=True, upload_to='./field360App/media/'),
        ),
    ]
