# Generated by Django 4.1.5 on 2023-04-04 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_piece_recto_alter_user_piece_verso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
