# Generated by Django 4.1.5 on 2023-04-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privilege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.privilege'),
        ),
    ]
